development:
  adapter: postgresql
  host: localhost
  username: maasa
  database: sample_app
test: &test
  adapter: postgresql
  host: localhost
  username: maasa
  database: sample_app_test

cucumber:
  <<: *test